// flow-typed signature: 2addb82376559d645e6b51ba8b361fd1
// flow-typed version: <<STUB>>/abs_v^1.3.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'abs'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'abs' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'abs/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'abs/lib/index.js' {
  declare module.exports: $Exports<'abs/lib/index'>;
}
