// flow-typed signature: 97e265e2cb51f4f15c7526646c7e4f85
// flow-typed version: <<STUB>>/eslint-plugin-import-order-autofix_v^0.8.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-import-order-autofix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-import-order-autofix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-import-order-autofix/lib/core/add-types' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import-order-autofix/lib/core/importType' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import-order-autofix/lib/core/staticRequire' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import-order-autofix/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-import-order-autofix/lib/rules/order' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-import-order-autofix/lib/core/add-types.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order-autofix/lib/core/add-types'>;
}
declare module 'eslint-plugin-import-order-autofix/lib/core/importType.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order-autofix/lib/core/importType'>;
}
declare module 'eslint-plugin-import-order-autofix/lib/core/staticRequire.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order-autofix/lib/core/staticRequire'>;
}
declare module 'eslint-plugin-import-order-autofix/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order-autofix/lib/index'>;
}
declare module 'eslint-plugin-import-order-autofix/lib/rules/order.js' {
  declare module.exports: $Exports<'eslint-plugin-import-order-autofix/lib/rules/order'>;
}
