// flow-typed signature: c9913e1258a43ae3cb35f406db214ef3
// flow-typed version: <<STUB>>/limiter_v^1.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'limiter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'limiter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'limiter/lib/rateLimiter' {
  declare module.exports: any;
}

declare module 'limiter/lib/tokenBucket' {
  declare module.exports: any;
}

declare module 'limiter/test/tokenbucket-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'limiter/index' {
  declare module.exports: $Exports<'limiter'>;
}
declare module 'limiter/index.js' {
  declare module.exports: $Exports<'limiter'>;
}
declare module 'limiter/lib/rateLimiter.js' {
  declare module.exports: $Exports<'limiter/lib/rateLimiter'>;
}
declare module 'limiter/lib/tokenBucket.js' {
  declare module.exports: $Exports<'limiter/lib/tokenBucket'>;
}
declare module 'limiter/test/tokenbucket-test.js' {
  declare module.exports: $Exports<'limiter/test/tokenbucket-test'>;
}
