// flow-typed signature: a4377f76dc0543a96ffa9765a90aa336
// flow-typed version: <<STUB>>/moment-weekday-calc_v^1.1.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment-weekday-calc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment-weekday-calc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'moment-weekday-calc/build/moment-weekday-calc.min' {
  declare module.exports: any;
}

declare module 'moment-weekday-calc/example/example_node' {
  declare module.exports: any;
}

declare module 'moment-weekday-calc/Gruntfile' {
  declare module.exports: any;
}

declare module 'moment-weekday-calc/src/moment-weekday-calc' {
  declare module.exports: any;
}

declare module 'moment-weekday-calc/test/weekdaycalc_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'moment-weekday-calc/build/moment-weekday-calc.min.js' {
  declare module.exports: $Exports<'moment-weekday-calc/build/moment-weekday-calc.min'>;
}
declare module 'moment-weekday-calc/example/example_node.js' {
  declare module.exports: $Exports<'moment-weekday-calc/example/example_node'>;
}
declare module 'moment-weekday-calc/Gruntfile.js' {
  declare module.exports: $Exports<'moment-weekday-calc/Gruntfile'>;
}
declare module 'moment-weekday-calc/src/moment-weekday-calc.js' {
  declare module.exports: $Exports<'moment-weekday-calc/src/moment-weekday-calc'>;
}
declare module 'moment-weekday-calc/test/weekdaycalc_test.js' {
  declare module.exports: $Exports<'moment-weekday-calc/test/weekdaycalc_test'>;
}
