// flow-typed signature: 6aea12185f42ac891a543d1009e90247
// flow-typed version: <<STUB>>/msexcel-builder-colorfix_v0.0.3/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'msexcel-builder-colorfix'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'msexcel-builder-colorfix' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'msexcel-builder-colorfix/lib/msexcel-builder' {
  declare module.exports: any;
}

declare module 'msexcel-builder-colorfix/test/i2a.test' {
  declare module.exports: any;
}

declare module 'msexcel-builder-colorfix/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'msexcel-builder-colorfix/lib/msexcel-builder.js' {
  declare module.exports: $Exports<'msexcel-builder-colorfix/lib/msexcel-builder'>;
}
declare module 'msexcel-builder-colorfix/test/i2a.test.js' {
  declare module.exports: $Exports<'msexcel-builder-colorfix/test/i2a.test'>;
}
declare module 'msexcel-builder-colorfix/test/test.js' {
  declare module.exports: $Exports<'msexcel-builder-colorfix/test/test'>;
}
