// flow-typed signature: f7a8789a0b9f86d3198fda2db5cfc194
// flow-typed version: <<STUB>>/msexcel-builder_v0.0.2/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'msexcel-builder'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'msexcel-builder' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'msexcel-builder/lib/msexcel-builder' {
  declare module.exports: any;
}

declare module 'msexcel-builder/test/i2a.test' {
  declare module.exports: any;
}

declare module 'msexcel-builder/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'msexcel-builder/lib/msexcel-builder.js' {
  declare module.exports: $Exports<'msexcel-builder/lib/msexcel-builder'>;
}
declare module 'msexcel-builder/test/i2a.test.js' {
  declare module.exports: $Exports<'msexcel-builder/test/i2a.test'>;
}
declare module 'msexcel-builder/test/test.js' {
  declare module.exports: $Exports<'msexcel-builder/test/test'>;
}
