// flow-typed signature: 606d6df70156b1d05afa379364700755
// flow-typed version: <<STUB>>/typpy_v^2.3.6/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'typpy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'typpy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'typpy/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'typpy/lib/index.js' {
  declare module.exports: $Exports<'typpy/lib/index'>;
}
