// flow-typed signature: 772c8678a7f93c7973e78128b18059c8
// flow-typed version: <<STUB>>/ul_v^5.2.9/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'ul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'ul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'ul/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'ul/lib/index.js' {
  declare module.exports: $Exports<'ul/lib/index'>;
}
